#!/usr/bin/env ruby

ENV['RACK_ENV'] = 'production'

Dir.chdir File.expand_path(File.dirname(__FILE__))

require 'bundler'
require File.join(File.expand_path(File.dirname(__FILE__)), 'config/config.rb')
require 'vegas'

$0 = 'coinpunk'

Vegas::Runner.new(Controller, 'coinpunk') do |runner, opts, app|
  runner.options[:skip_launch] = true
end