#!/usr/bin/env ruby

puts "WARNING: This is currently broken. Use this for now: bundle exec rackup -s puma -p PORTNUMBERYOUWANT If you upgraded from master branch, DON'T USE THIS! Use the tagged releases."

ENV['RACK_ENV'] = 'production'

Dir.chdir File.expand_path(File.dirname(__FILE__))

require 'bundler'
require File.join(File.expand_path(File.dirname(__FILE__)), 'config/config.rb')
require 'vegas'

$0 = 'coinpunk'

Vegas::Runner.new(Controller, 'coinpunk') do |runner, opts, app|
  runner.options[:skip_launch] = true
end